name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN  }}
          TARGET_REPO: AltQ1231/altq1231.github.io
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: src/.vuepress/dist/
